const people = [
  {
    name: "divjot",
    age: 13,
    class: 9,
    section: "b",
    gender: "male",
    roles: ["dev", "prog", "robotics"],
    yearJoined: 2023,
    noOfEventsDone: 1,
    phoneNo: "9871137216",
    email: "divjot2913@outlook.com",
  },
  {
    name: "manan",
    age: 13,
    class: 9,
    section: "d",
    gender: "male",
    roles: ["dev", "gaming"],
    yearJoined: 2023,
    noOfEventsDone: 0,
    phoneNo: "8076408261",
    email: "aswani.manan@outlook.com",
  },
  {
    name: "agastya",
    age: 13,
    class: 9,
    section: "d",
    gender: "male",
    roles: ["dev", "prog", "gaming"],
    yearJoined: 2023,
    noOfEventsDone: 0,
    phoneNo: "9810499031",
    email: "agastyakwatra@hotmail.com",
  },
  {
    name: "pushan",
    age: 15,
    class: 11,
    section: "c",
    gender: "male",
    roles: ["vice pres", "web dev exec", "quiz exec"],
    yearJoined: 1970,
    noOfEventsDone: Infinity,
    phoneNo: "9911606799",
    email: "pushanban@gmail.com",
  },
  {
    name: "suryansh",
    age: 16,
    class: 12,
    section: "c",
    gender: "male",
    roles: ["pres", "robotics exec", "3d av"],
    yearJoined: 1970,
    noOfEventsDone: Infinity,
    phoneNo: "9958062729",
    email: "ss10suryansh@gmail.com",
  },
  {
    name: "bhavna",
    age: 15,
    class: 11,
    section: "e",
    gender: "female",
    roles: ["chief exec", "design exec", "gd"],
    yearJoined: 1970,
    noOfEventsDone: Infinity,
    phoneNo: "9599874344",
    email: "jainbhavna2007@gmail.com",
  },
  {
    name: "noel",
    age: 16,
    class: 12,
    section: "d",
    gender: "male",
    roles: ["advisor", "3d av exec", "gaming exec"],
    yearJoined: 1970,
    noOfEventsDone: Infinity,
    phoneNo: "8929057870",
    email: "noeltudu7@gmail.com",
  },
  {
    name: "manas k",
    age: 16,
    class: 12,
    section: "c",
    gender: "male",
    roles: ["advisor", "prog exec"],
    yearJoined: 1970,
    noOfEventsDone: Infinity,
    phoneNo: "9319816275",
    email: "manaskaushik26@gmail.com",
  },
  {
    name: "anya",
    age: 16,
    class: 12,
    section: "b",
    gender: "female",
    roles: ["gd exec", "design"],
    yearJoined: 1970,
    noOfEventsDone: Infinity,
    phoneNo: "98118 49619",
    email: "anyagupta787@gmail.com",
  },
  {
    name: "reya",
    age: 13,
    class: 9,
    section: "e",
    gender: "female",
    roles: ["prog", "design", "gd"],
    yearJoined: 2022,
    noOfEventsDone: Infinity,
    phoneNo: "9711393394",
    email: "reya.kaloya@gmail.com",
  },
];

export default people;
